all:
	javac portal.java
	javac backpack_user.java
	javac instructor.java
	javac student.java
	javac lectureSlide.java
	javac lectureVideo.java
	javac lectureMaterial.java
	javac assignment.java
	javac quiz.java
	javac assessment.java