all: game carpet tile soft_toy calculator bucket
game:
	javac game.java
carpet:
	javac carpet.java
tile:
	javac tile.java
soft_toy:
	javac soft_toy.java
calculator:
	javac calculator.java
bucket:
	javac bucket.java